logging:
  level:
    root: INFO
    com.tcs.busbuddy: DEBUG   # Enable detailed logs only for your app package
  file:
    name: logs/busbuddy-app.log   # All logs will be saved here
  logback:
    rollingpolicy:
      clean-history-on-start: true
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{36}) | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n"
